import {
  Menu,
  Bell,
  LayoutDashboard,
  MessageCircle,
  Mail,
  Radio,
  Film,
  Building,
  Calendar,
  Receipt,
  BookOpen,
  MoreHorizontal,
  Plus,
  Send,
  History,
  CheckSquare,
  Search,
  CircleUser,
  DollarSign,
  TrendingUp,
  AlertCircle,
  X,
  ChevronLeft,
  ChevronRight,
  User,
  Clock,
  Music,
  Eye,
} from "lucide-react";

export const Icons = {
  menu: Menu,
  bell: Bell,
  dashboard: LayoutDashboard,
  chat: MessageCircle,
  email: Mail,
  radio: Radio,
  movie: Film,
  building: Building,
  calendar: Calendar,
  receipt: Receipt,
  book: BookOpen,
  more: MoreHorizontal,
  plus: Plus,
  send: Send,
  history: History,
  task: CheckSquare,
  search: Search,
  addCircle: CircleUser,
  dollar: DollarSign,
  trending: TrendingUp,
  alert: AlertCircle,
  close: X,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  user: User,
  clock: Clock,
  music: Music,
  eye: Eye,
};
