import {
  Menu,
  Bell,
  LayoutDashboard,
  MessageCircle,
  Mail,
  Radio,
  Film,
  Building,
  Calendar,
  Receipt,
  BookOpen,
  FileText,
  MoreHorizontal,
  Plus,
  Send,
  History,
  CheckSquare,
  Search,
  CircleUser,
  DollarSign,
  TrendingUp,
  AlertCircle,
  X,
  ChevronLeft,
  ChevronRight,
  User,
  Clock,
  Music,
  Eye,
  CheckCircle,
  Clipboard,
  Users,
  BarChart,
  Edit,
  Sun,
  Moon,
  Sunrise,
  Sunset,
  ShoppingCart,
  Mic,
  MicOff,
  Volume2,
  Settings,
  Github,
  Network,
  Shield,
  Key,
  Zap,
  Globe,
  Bot,
  Cpu,
  Link,
  Activity,
  RefreshCw,
  Copy,
  Check,
  GitBranch,
  Upload,
  Lock,
  Unlock,
  Server,
  Terminal,
  Sparkles,
  Command,
} from "lucide-react";

export const Icons = {
  menu: Menu,
  bell: Bell,
  dashboard: LayoutDashboard,
  chat: MessageCircle,
  email: Mail,
  radio: Radio,
  movie: Film,
  building: Building,
  calendar: Calendar,
  receipt: Receipt,
  book: BookOpen,
  fileText: FileText,
  more: MoreHorizontal,
  plus: Plus,
  send: Send,
  history: History,
  task: CheckSquare,
  search: Search,
  addCircle: CircleUser,
  dollar: DollarSign,
  trending: TrendingUp,
  alert: AlertCircle,
  close: X,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  user: User,
  clock: Clock,
  music: Music,
  eye: Eye,
  checkCircle: CheckCircle,
  clipboard: Clipboard,
  users: Users,
  barChart: BarChart,
  edit: Edit,
  mail: Mail,
  sun: Sun,
  moon: Moon,
  sunrise: Sunrise,
  sunset: Sunset,
  shoppingCart: ShoppingCart,
  mic: Mic,
  micOff: MicOff,
  volume: Volume2,
  settings: Settings,
  github: Github,
  network: Network,
  shield: Shield,
  key: Key,
  zap: Zap,
  globe: Globe,
  bot: Bot,
  cpu: Cpu,
  link: Link,
  activity: Activity,
  refresh: RefreshCw,
  copy: Copy,
  check: Check,
  gitBranch: GitBranch,
  upload: Upload,
  lock: Lock,
  unlock: Unlock,
  server: Server,
  terminal: Terminal,
  sparkles: Sparkles,
  command: Command,
};
